### ISSUE TITLE
Any way to disable AVC?

### ISSUE THREAD

**Issue by Svish** [CYBUTEK/KSPAddonVersionChecker#16]
I'm using CKAN to check for updates, and would like for AVC to not do it as it often slows down the launch of KSP (my internet connection is horrible...).

Is there a way to disable it?

Would also be good with a "I know this mod is outdated, thanks for telling me, really, but you don't have to remind me every time I launch the game until either the version of the game or the mod changes again" kind of button.

**Comment by ericfriesen** [comment]
Use Zero MiniAVC.
