### ISSUE TITLE
KSP-CKAN inflator bot unable to reach ksp-avc.cybutek.net

### ISSUE THREAD

**Issue by DasSkelett** [CYBUTEK/KSPAddonVersionChecker#23]
Hey @CYBUTEK,

since around 08:00 UTC today, the CKAN inflator bot is unable to download remote version files from http://ksp-avc.cybutek.net, all requests are timing out.

<img src="https://user-images.githubusercontent.com/28812678/112362408-b0acc480-8cd4-11eb-87b9-97dbe64ab759.png" alt="KSP-CKAN status page showing inflation warnings due to timeouts" height="400" />

http://status.ksp-ckan.space/
Around 60 mods are affected by this.

We are quite certain that we didn't change anything on our side that could cause this.
Did you maybe do some changes that causes all requests from our bot to time out? Maybe some sort of bot protection?

Modders are still using this site very actively to host their remote version files, which allows them to update the compatibility after the release. It would be nice if CKAN could keep using this as well, to make sure it always has correct and up-to-date compatibility data.

Thanks!

(@HebaruSan FYI)

**Comment by HebaruSan** [comment]
> Around 60 mods are affected by this.

Luckily only about 5 of them now have wrong metadata because of it:

https://github.com/KSP-CKAN/CKAN-meta/compare/0c33c7a...13e799944a

**Comment by CYBUTEK** [comment]
I've had a look and nothing has changed at my end...  There's no bot protection on the website, but I cannot rule out my hosting provider trying to be "helpful".  Looked through the logs that I have access to and the last CKAN request was at 08:09:03 UTC.

Are you able to try manually accessing the ksp-avc website from the CKAN server, via ssh and doing a curl to confirm that the IP is in-fact being blocked?

**Comment by DasSkelett** [comment]
Thanks for the quick response!
@techman83 did some testing, and it turns out that curl requests from the same server do in fact work.

Another guess of mine is that the hosting provider might be "smart" and blocks the combination of user agent string and IP address. We didn't try that out yet, though.

We keep investigating.

**Comment by HebaruSan** [comment]
We seem to be in the middle of a successful pass at the moment, the remote data is coming back:

https://github.com/KSP-CKAN/CKAN-meta/compare/27e69b9649...fbd5f41285

**Comment by DasSkelett** [comment]
Really weird. I'm closing this issue again, since the timeouts are gone for two days now, and we can't confirm (nor deny) that this was in fact a issue on your side.

Thanks a lot for taking a look @CYBUTEK!

**Comment by HebaruSan** [comment]
Hi @CYBUTEK,

FYI, the server is returning 500 statuses now, resetting some versioning metadata:

https://ksp-avc.cybutek.net/

Here's hoping it's a simple problem to fix!

FYI to @NathanKell.

**Comment by CYBUTEK** [comment]
Sorry about that...  Managed to get it all back up and running again now :)

**Comment by HebaruSan** [comment]
Thank you! :heart:

**Comment by HebaruSan** [comment]
Hi @CYBUTEK, the 500 errors are happening again:
https://ksp-avc.cybutek.net/

**Comment by CYBUTEK** [comment]
Thanks for the heads up... Hopefully it's fixed now.

**Comment by HebaruSan** [comment]
Hi @CYBUTEK, sorry to bother you again, but the server is acting up again. Thanks for keeping this old thing running!

**Comment by CYBUTEK** [comment]
Should be back up now...  I'm so sorry about that, the upgrade from Debian 10 to 11 wasn't very smooth at all, as the VM doesn't like the new kernel 🙄

**Comment by StonesmileGit** [comment]
Hi @CYBUTEK, looks like the same issue has appeared again. If it is not the same as before though, I think HebaruSan would be best to ping, as they directed me here.

**Comment by CYBUTEK** [comment]
Sorry for the delay...  Thanks for letting me know and it should all be up again.

**Comment by NathanKell** [comment]
Thanks!! ❤️

**Comment by NathanKell** [comment]
@CYBUTEK ( cc @HebaruSan ) looks like this happened again

**Comment by HebaruSan** [comment]
@NathanKell, It's slightly different this time, the CKAN bot is getting timed out, but the server is up when I try it locally. @CYBUTEK, was some kind of whitelisting/blacklisting/throttling added recently? Is it possible to check the logs to figure out why requests might be getting timed out?

**Comment by CYBUTEK** [comment]
I'm not sure why it has stopped working, there have been no changes to the server recently.  I have updated and did a reboot of the server to see if that might solve the issue, but if it doesn't I'll go diving through the logs tomorrow.

**Comment by HebaruSan** [comment]
Looks like it fixed itself a few hours ago:

https://github.com/KSP-CKAN/CKAN-meta/compare/8e962db794...6d294bfaca
