### ISSUE TITLE
Missing source file Utils.c

### ISSUE THREAD

**Issue by MonArchangel** [CYBUTEK/KSPAddonVersionChecker#5]
Hi, 

Please refer line 206 of ToolbarWindows.cs. Source text refers to an external class method Utils.GetTexture. VS2013 Solution explorer also references Utils.cs and flags it as missing.

Please check in the missing file .

Have a nice day!!!

Archangel

**Comment by CYBUTEK** [comment]
Fixed in https://github.com/CYBUTEK/KSPAddonVersionChecker/commit/61fdc3d9ffd8edf9ef11fb68c2ccdd9cdd3ba253
